language: nodejs
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
install:
  - npm i mocha -g
  - npm i
script:
  - sh ./.travis-ssh.sh
  - npm test
  - ps aux | grep tail
sudo: true